[package]
name = "korrekt"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2022_08_19" }
env_logger = "0.9.0"
log = "0.4.17"
try-catch = "0.2.2"
anyhow = "1.0.71"
regex = "1.8.4"

[patch."https://github.com/privacy-scaling-explorations/halo2.git"]
halo2_proofs = { version = "0.2.0", git = "https://github.com/quantstamp/halo2.git" }

[features]
default = []
benches = []
